
name: Publish release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-universal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Configure dependencies
      run: ./configure.sh ${{ matrix.platform }} z3-static
    - name: Package & Publish extension (universal)
      run: npx vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

  publish-macos:
    runs-on: ubuntu-latest
    needs: [publish-universal]
    strategy:
      matrix:
        platform: [darwin-x64, darwin-arm64]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Configure dependencies
      run: ./configure.sh ${{ matrix.platform }}
    - name: Package & Publish extension (platform-specific)
      run: npx vsce publish --target ${{ matrix.platform }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}