
name: Publish release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, darwin-x64, darwin-arm64]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        include:
          - os: linux-x64
            z3_static: z3-static
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Configure dependencies
      run: ./configure.sh ${{ matrix.platform }} ${{ matrix.z3_static }}
    - name: Package & Publish extension (platform-specific)
      if: ${{ matrix.platform != 'linux-x64' }}
      run: npx vsce publish --target ${{ matrix.platform }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Package & Publish extension (universal)
      if: ${{ matrix.platform == 'linux-x64' }}
      run: npx vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
