
name: Publish release

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  #release:
  #  types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x64, darwin-x64, darwin-arm64]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        include:
          - platform: linux-x64
            target:
            z3_static: z3-static
          - platform: darwin-x64
            target: --target darwin-x64
          - platform: darwin-arm64
            target: --target darwin-arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Configure dependencies
      run: ./configure.sh ${{ matrix.platform }} ${{ matrix.z3_static }}
    - name: Package extension
      run: npx vsce package ${{ matrix.target }}
    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}
        path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Download extension artifacts
        uses: actions/download-artifact@v3
      - name: Publish extension
        run: find . -iname *.vsix
        #run: npx vsce publish --packagePath $(find . -iname *.vsix)
        #env:
        #  VSCE_PAT: ${{ secrets.VSCE_PAT }}
